config/routes.rb
App60::Application.routes.draw do
  # User
  root 'user#index'
  get 'user' => redirect('/')
  get 'user/index' => redirect('/')
  get 'user/about', as: 'about'
  get 'user/contact', as: 'contact'
  get 'user/tutorial', as: 'tutorial'
  get 'share/:id', to: 'user#index', as: 'share_narrative'

  # Narratives
  get 'sunburst' => 'narratives#sunburst'
  get 'narratives/:id/play', to: 'narratives#play', as: 'play_narrative'
  post 'narratives/:id/comment/', to: 'narratives#comment', as: 'comment_add'
  delete 'narratives/:id/comment/:comment_id/remove/', to: 'narratives#remove_comment', as: 'remove_comment'
  post 'narratives/:id/flag/', to: 'narratives#flag', as: 'increment_flag'
  post 'narratives/:id/agree', to: 'narratives#agree', as: 'agree_with_narrative'
  post 'narratives/:id/undo_agree', to: 'narratives#undo_agree', as: 'undo_agree_with_narrative'
  post 'narratives/:id/disagree', to: 'narratives#disagree', as: 'disagree_with_narrative'
  post 'narratives/:id/undo_disagree', to: 'narratives#undo_disagree', as: 'undo_disagree_with_narrative'
  post 'narratives/save', as: 'save_narratives'
  resources :narratives

  # Admin
  get 'admin', to: 'narratives#index', as: 'admin_list'
  get 'admin/setting', to: 'narratives#setting', as: 'admin_setting'
  post 'admin/change', to: 'admin#change_password', as: 'change_password'
  post 'admin/add', to: 'admin#add_admin', as: 'add_admin'
  get 'admin/login',  to: 'sessions#new', as: 'signin'
  delete 'admin/logout', to: 'sessions#destroy', as: 'signout'
  post 'admin/upload', as: 'upload_narrative'
  get 'admin/forget', to: 'sessions#forget_password', as: 'forget_password'
  post 'admin/send', to: 'sessions#send_password', as: 'send_password'
  get 'admin/*any' => redirect('/admin')
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/narrative.rb
class Narrative < ActiveRecord::Base
  has_many :audios, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :n_comments, dependent: :destroy
  validates :nar_name, presence: true
  validates :nar_path, presence: true
end

app/controllers/narratives_controller.rb
# encoding: utf-8
class NarrativesController < ApplicationController
  include NarrativesHelper
  before_action :set_narrative, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, :except => [:play, :comment, :flag, :agree, :disagree, :undo_agree, :undo_disagree], :unless => :format_json?

  # GET /narratives
  # GET /narratives.json
  def index
    @narratives = Narrative.all
    published_narratives = Narrative.where(is_published: true)
    render_to_home(narratives_json(published_narratives))
  end

  def setting
  end

  # GET /narratives/1
  # GET /narratives/1.json
  def show
    @narrative = Narrative.find(params[:id])
    
    respond_to do |format|
      format.html
      # Support JSONP. Read more: http://henrysztul.info/post/14970402595/how-to-enable-jsonp-support-in-a-rails-app
      format.json { render :json => narrative_json(@narrative), :callback => params[:callback] }
    end
  end

  # GET /sunburst
  # GET /sunburst.json
  def sunburst
    @narratives = Narrative.all
    published_narratives = Narrative.where(is_published: true)
    render_to_home(sunburst_json(published_narratives))
  end

  # GET /narratives/new
  def new
    @narrative = Narrative.new
  end

  # GET /narratives/1/edit
  def edit
  end
  
  # GET /narratives/1/play/
  def play
    selected_narrative_id = params[:id]
    @narrative = Narrative.find(selected_narrative_id)
    audio_array = []
    fill_audio_array audio_array, selected_narrative_id
    @audio_json = audio_array.to_json.html_safe
    @comments = get_comments_for_narrative(selected_narrative_id)
    @audio_count = audio_array.size
    @share_link = share_narrative_url params[:id].strip
    Narrative.increment_counter(:num_of_view, selected_narrative_id)
  end

  # POST narratives/1/comment
  def comment
    narrative_id = params[:id]
    NComment.create(content: params[:user_submitted_comment], narrative_id: narrative_id)
    @comments = get_comments_for_narrative(narrative_id)
    respond_to do |format|
      format.js
    end
  end
  
  # DELETE narratives/1/comment/1/remove/
  def remove_comment
    narrative_id = params[:id]
    comment = NComment.find(params[:comment_id])
    comment.update(:content => 'Commentaire supprimé / Comment removed')
    @comments = get_comments_for_narrative(narrative_id)
    respond_to do |format|
      format.js { render 'comment.js.erb' }
    end
  end

  # POST narratives/1/flag
  def flag
    narrative_id = params[:id]
    if (params.has_key?(:comment_id) && params[:comment_id] != "" && !is_flagged?("comment", params[:comment_id]))
      NComment.increment_counter(:num_flags, params[:comment_id])
      FlagMailer.flag_comment_email(narrative_id, params[:comment_id], params[:flag]).deliver
      save_flagged_content("comment", params[:comment_id])
    elsif (!is_flagged? "narrative", narrative_id.to_s)
      Narrative.increment_counter(:num_of_flagged, narrative_id)
      FlagMailer.flag_narrative_email(narrative_id, params[:flag]).deliver
      save_flagged_content("narrative", narrative_id)
    end
    redirect_to(:action => "play", :id => narrative_id)
  end
  
  # POST narratives/1/agree
  def agree
    is_ok = Narrative.increment_counter(:num_of_agree, params[:id])
    return_status_code is_ok
  end
  
  # POST narratives/1/disagree
  def disagree
    is_ok = Narrative.increment_counter(:num_of_disagree, params[:id])
    return_status_code is_ok
  end
  
  # POST narratives/1/undo_agree
  def undo_agree
    is_ok = Narrative.decrement_counter(:num_of_agree, params[:id])
    return_status_code is_ok
  end
  
  # POST narratives/1/undo_disagree
  def undo_disagree
    is_ok = Narrative.decrement_counter(:num_of_disagree, params[:id])
    return_status_code is_ok    
  end
  
  # POST /narratives
  # POST /narratives.json
  def create
    @narrative = Narrative.new(narrative_params)

    respond_to do |format|
      if @narrative.save
        format.html { redirect_to @narrative,
                                  notice: 'Narrative was successfully created.' }
        format.json { render action: 'show', status: :created, location: @narrative }
      else
        render_after_fail(format, 'new')
      end
    end
  end

  # PATCH/PUT /narratives/1
  # PATCH/PUT /narratives/1.json
  def update
    respond_to do |format|
      if @narrative.update(narrative_params)
        format.html { redirect_to admin_list_path }
        format.json { head :no_content }
        flash[:success] = "The narrative has been updated."
      else
        #render_after_fail(format, 'edit')
        flash[:error] = "Fail.The narrative cannot be updated."
      end
    end
  end

  # POST /narratives/save
  def save
    # Convert hash keys from String to Int
    converted_params = Hash[params[:narrative_attributes].map {|k, v| [k.to_i, v] }]
    # Whitelist params
    safe_params = ActionController::Parameters.new(converted_params)
    # Track success of save
    is_saved = true
    # Commit all updates in a single transaction
    Narrative.transaction do
      # ActiveRecord guarantees that only changed objects will be saved in the transaction
      Narrative.all.each do |narrative|
        is_saved = is_saved and narrative.update(safe_params.require(narrative.id).permit(:nar_name, :language_id, :category_id, :is_published))
      end
    end
    # Flash save status
    if is_saved
      flash[:success] = "The narratives have been saved."
    else
      flash[:error] = "There was a problem saving the narratives..."
    end
    redirect_to admin_list_path
  end

  # DELETE /narratives/1
  # DELETE /narratives/1.json
  def destroy
    FileUtils.rm_rf(Rails.public_path + @narrative.nar_path)
    @narrative.destroy
    respond_to do |format|
      format.html { redirect_to admin_list_path }
      format.json { head :no_content }
    end
    flash[:success] = "The narrative has been delete."
  end

  private
    def return_status_code is_ok
      respond_to do |format|
        if is_ok == 1
          format.json { head :ok }
        else
          format.json { head :error }
        end 
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_narrative
      @narrative = Narrative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def narrative_params
      params.require(:narrative).permit(:nar_name, :nar_path, :language_id,
                                        :category_id, :first_image,
                                        :num_of_view, :num_of_agree,
                                        :num_of_disagree, :num_of_flagged,
                                        :create_time, :is_published)
    end

    def render_after_fail format, act
      format.html { render action: act }
      format.json { render json: @narrative.errors, status: :unprocessable_entity }
    end

    def render_to_home json_data
      respond_to do |format|
        format.html
        # Support JSONP. Read more: http://henrysztul.info/post/14970402595/how-to-enable-jsonp-support-in-a-rails-app
        format.json { render :json => json_data, :callback => params[:callback] }
      end
    end

    def require_login
      unless signed_in?
        redirect_to signin_path
      end
    end
    
    def format_json?
      request.format.json?
    end
end

app/helpers/narratives_helper.rb
module NarrativesHelper

  def narratives_json(narratives)

    list = narratives.order(:category_id).map do |narrative|
      narrative_json(narrative)
    end
    {:name => "Narratives", :children => list
    }.to_json
  end

  def narrative_json(narrative)
        { :id => "#{narrative.id}",
          :name => narrative.nar_name,
          :language => narrative.language_id,
          :numberAgree => narrative.num_of_agree,
          :numberDisagree => narrative.num_of_disagree,
          :numberViews => narrative.num_of_view,
          :numberComments => narrative.n_comments.count,
          :narrativeID => narrative.id,
          :category => narrative.category_id,
          :uploadTime => narrative.updated_at
        }
  end

  def sunburst_json(narratives)

    list = narratives.group(:category_id).count.map do |key, value|
      sunburst_list(key, value)
    end

    {
      :name => "Narratives", :children => list
    }.to_json
  end

  def sunburst_list(key, value)
    {
      :category_id => key,
      :count => value
    }
  end

  def get_comments_for_narrative narrative_id
    NComment.where(narrative_id: narrative_id).order("created_at DESC")
  end

  def get_language_name language_id
    Language.find(language_id).language_name
  end

  def get_category_name category_id
    Category.find(category_id).category_name
  end

  def get_flagged_content    
    flagged_content_array = Array.new
    if (cookies[:flagged])
      flagged_string = cookies[:flagged]
      flagged_string.lines.each do |line|
          flagged_content_array << line.split(',').map(&:chomp)
      end
    end
    return flagged_content_array
  end
  
  def save_flagged_content type, id
    flagged_str = ""
    flagged_content = get_flagged_content
    flagged_content.push([type, id.to_s])
    
    flagged_content.each do |line|
      flagged_str  << line.join(",") + "\n"
    end
    cookies[:flagged] = flagged_str
  end
  
  def is_flagged? passed_type, passed_id
    flagged_content = get_flagged_content
    !flagged_content.select{ |type, id| type == passed_type.to_s && id == passed_id.to_s}.empty?
  end

  def fill_audio_array audio_array, selected_narrative_id
    images = Image.where(narrative_id: selected_narrative_id)
    default_image_path = images.first.try(:image_path) || "default_narrative_image.jpg"
    Audio.where(narrative_id: selected_narrative_id).each do |audio|
      image_path = images.where("image_number <= ?", audio.audio_number).last.try(:image_path) || default_image_path
      audio_array.push(mp3: root_url + audio.audio_path, poster: root_url + image_path)
    end
  end

end

app/views/narratives/edit.html.erb
<h1>Editing narrative</h1>

<%= render 'form' %>

<%= link_to 'Show', @narrative %> |
<%= link_to 'Back', narratives_path %>

app/views/narratives/index.html.erb
    <!-- <div class="navbar navbar-inverse navbar-fixed-top" role="navigation"> -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand">VousDélibérez! <span class="glyphicon glyphicon-flash"></span> YouDeliberate!</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="list-spacer">&nbsp;</li>
            <li><a class="fancybox" href="<%= admin_list_path %>">Récits <span class="glyphicon glyphicon-flash"></span> Narratives</a></li>
            <li><a class="fancybox" href="<%= admin_setting_path %>">Paramètres <span class="glyphicon glyphicon-flash"></span> Settings</a></li>
            <li class="list-spacer">&nbsp;</li>
            <li class="list-spacer" align="right"><%= link_to "Déconnexion/Logout", signout_path, method: "delete" %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content container -->
    <div class="container">

      <!-- page headline -->
      <div class="header-section"><br/></div>

      <!-- Upload narrative section -->
      <div class="col-lg-12">
      	<div class="panel panel-primary">
          <div class="panel-heading"><h4>Télécharger des récits&nbsp;&nbsp;<span class="glyphicon glyphicon-flash"></span>&nbsp;&nbsp;Upload Narratives</h4></div>
          <div>
            <h2><p class="title">Please choose a zip file:</p></h2>
			<%= form_tag(upload_narrative_path, multipart: true) do %>
			  <div class="with-small-left-margin"><%= file_field_tag 'narrative', accept: 'application/zip'%></div>
			  <div><%= hidden_field_tag 'upload_path' %></div>
			  <div class="with-left-margin with-bottom-margin"><%= submit_tag("Upload") %></div>
			<% end %>
		  </div>
      	</div>
      </div><!-- End upload narrative section -->

      <div><br/><br/></div>

      <!-- Listing narrative section -->
      <div class="col-lg-12">
      	<div class="panel panel-primary">
          <div class="panel-heading"><h4>Liste des récits&nbsp;&nbsp;<span class="glyphicon glyphicon-flash"></span>&nbsp;&nbsp;Listing Narratives</h4></div>
			<div class="table-responsive with-padding">
        <%= form_tag(save_narratives_path, method: "post") do %>
        <table class="tablesorter">
          <thead>
            <tr>
              <th class="header">Name</th>
              <th class="header">Language</th>
              <th class="header">Category</th>
              <th>Published</th>
              <th class="header">View&nbsp;&nbsp;&nbsp;</th>
              <th class="header">Agree&nbsp;&nbsp;&nbsp;</th>
              <th class="header">Disagree&nbsp;&nbsp;&nbsp;</th>
              <th class="header">Flagged&nbsp;&nbsp;&nbsp;</th>
              <th class="header">Create Time</th>
              <th class="header">Upload Time</th>
              <th colspan="2"></th>
            </tr>
          </thead>
          
          <tbody>
           
           <% language_all = Language.all.collect {|p| [ p.language_name, p.id ] } %>
           <% category_all = Category.all.collect {|p| [ p.category_name, p.id ] } %>
           <% @narratives.each do |narrative| %>
           <% form_hash = "narrative_attributes[#{narrative.id}]" %>
           <tr>
            <td><%= text_field(form_hash, :nar_name, value: narrative.nar_name) %></td>
            <td><%= select(form_hash, :language_id, options_for_select(language_all, narrative.language_id) ) %></td>
            <td><%= select(form_hash, :category_id, options_for_select(category_all, narrative.category_id) ) %></td>
            <td>
              <input name="<%= form_hash %>[is_published]" type="hidden" value="0" />
              <input <%= 'checked="checked"' if narrative.is_published %> id="<%= form_hash %>_is_published" name="<%= form_hash %>[is_published]" type="checkbox" value="1" />
            </td>
            <td><%= narrative.num_of_view %></td>
            <td><%= narrative.num_of_agree %></td>
            <td><%= narrative.num_of_disagree %></td>
            <td><%= narrative.num_of_flagged %></td>
            <td><%= narrative.create_time.to_formatted_s(:db) %></td>
            <td><%= narrative.updated_at.to_formatted_s(:db) %></td>
            <td><a href="#" class="btn btn-default btn-xs" data-narrative-id="<%= narrative.id %>">Play</a></td>
            <td><%= link_to 'Delete', narrative, method: :delete, data: { confirm: 'Do you really want to delete this narrative?' }, :class => "btn btn-default btn-xs", :id => "admin-delete-narrative" + narrative.id.to_s %></td>
          </tr>
          <% end %>
          
        </tbody>
        
      </table>
      <%= button_tag "Save", class: "btn btn-primary btn-lg", id: "admin-save-all-narratives" %>
      <%= link_to "Cancel", admin_list_path, class: "btn btn-primary btn-lg", id: "admin-cancel-changes" %>
      <% end %>
			</div>
          </div>
        </div>
      </div> <!-- End listing narrative section -->

    </div><!-- End content container -->

app/views/narratives/new.html.erb
<h1>New narrative</h1>

<%= render 'form' %>

<%= link_to 'Back', narratives_path %>

app/views/narratives/play.html.erb
<% content_for(:head) do %>
	<%= javascript_include_tag "jquery.jplayer.min" %>
	<%= javascript_include_tag "jplayer.playlist.min" %>
	<%= stylesheet_link_tag "jplayer.blue.monday" %>
  <script type="text/javascript">
  //<![CDATA[
  var playlistDetails = <%= @audio_json %>;
  var myPlaylist;
	$(document).ready(function(){
	  var currentTrack = $("#jp-current-track");
	  myPlaylist = new jPlayerPlaylist({
	    jPlayer: "#jquery_jplayer_1",
	    cssSelectorAncestor: "#jp_container_1"
	    },
	    playlistDetails,{
	      playlistOptions: {
	          autoPlay: false
	      },
	      swfPath: "js",
	      //solution: "flash, html",
	      solution: "html",
	      supplied: "webmv, ogv, m4v, oga, mp3",
	      smoothPlayBar: false,
	      keyEnabled: true,
	      audioFullScreen: true,
	      play: setTrackId
	    });

	  function setTrackId(e) {
	  	var trackId = myPlaylist.current + 1;
	    currentTrack.text(trackId);
	    window.paginate(trackId)
	  }
	  
	  jQuery('.btn').tooltip({html:true});
	  $('.flag-content-button').on("click", function() {
	  		var commentId = $(this).data('comment-id');
	 		$("#comment_id").val(commentId);
	  });
	  
	  
	  $('#agree-button, #disagree-button').on("click", function() {
	  	var that = $(this),
	  	voteIncr = 1,
	  	oppositeAction = $('#' + that.data('opposite-id'));
	  	
	  	// If the opposite vote was already cast (ie agree is the opposite of disagree and vice-versa)
	  	if (oppositeAction.data('vote-submitted')) {
	  		youDeliberate.updateVoteCountBy(oppositeAction, -1);
			youDeliberate.swapAndSubmit(oppositeAction);
	  	}
	  	
	  	if (that.data('vote-submitted')) {
	  		voteIncr = -1;
	  	}
	  	youDeliberate.updateVoteCountBy(that, voteIncr); 
	  	youDeliberate.swapAndSubmit(that);
	  	
	  })
	  
	  var youDeliberate = {
	  	// Submit request to update the vote count and swap the primary and secondary actions (ie, agree and undo_agree)
	  	swapAndSubmit: function(that) {
	  		var url = that.attr('data-ajax-primary-action');

			// Invert the vote-submitted field
			that.data('vote-submitted', !that.data('vote-submitted'));

	  		// Swap the actions to allow the user to undo what they've just done.
		  	that.attr('data-ajax-primary-action', that.attr('data-ajax-secondary-action'));
		  	that.attr('data-ajax-secondary-action', url);

		  	// Send out request
		  	$.ajax({
				url: url,
				type: 'POST'
			})
	  	},
	  	
	  	// Locally update visual display (instead of updating it from db values)
	  	updateVoteCountBy: function(that, x) {
	  		if (x > 0) { that.addClass("active");
	  		} else { that.removeClass("active"); }
	  		
	  		dataField = $('#' + that.data('display-id'));
			dataField.html(parseInt(dataField.html()) + x); 		
	  	}
	  	
	  }
	  
	});
	//]]>
	function playTrack(n) {
		myPlaylist.play(n - 1);
	}
	</script>
<% end %>

<div>
	<div id="narrative" align="center">
		<div class="input-group">
			<span class="input-group-addon"><span class="glyphicon glyphicon-link"></span></span>				
			<input id="share_link" type="text" onClick="this.select();" readonly="readonly" value="<%= @share_link %>" class="form-control" placeholder="">
		</div>
		<h1><small>Narrative name: <%= @narrative.nar_name %></small></h1>
		<div data-id="media_element">
      <%= render "jp" %>
		</div>
		</br>

		</br>
		<div class="btn-group" id="single-view-tooltip">
			<button id="agree-button" data-opposite-id="disagree-button" type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="D'accord / Agree" data-display-id="num-agree-votes" data-vote-submitted="false" data-ajax-primary-action="<%= agree_with_narrative_path(@narrative.id) %>", data-ajax-secondary-action="<%= undo_agree_with_narrative_path(@narrative.id) %>">
				<span class="glyphicon glyphicon-thumbs-up"></span>
				<span id="num-agree-votes"><%= @narrative.num_of_agree %></span>
			</button>
 			<button id="disagree-button" data-opposite-id="agree-button" type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Pas d'accord / Disagree" data-display-id="num-disagree-votes" data-vote-submitted="false" data-ajax-primary-action="<%= disagree_with_narrative_path(@narrative.id) %>", data-ajax-secondary-action="<%= undo_disagree_with_narrative_path(@narrative.id) %>">
 				<span class="glyphicon glyphicon-thumbs-down"></span>
 				<span id="num-disagree-votes"><%= @narrative.num_of_disagree %></span>
 			</button>
			<%= render 'flag_button', :this_type => "narrative", :this_id => @narrative.id, :comment_id => nil, :num_flags => @narrative.num_of_flagged %>
			<button type="button" class="btn btn-default" disabled="disabled"><span class="glyphicon glyphicon-eye-open">&nbsp;<%= @narrative.num_of_view %></span></button>
		</div>
	</div>
	<div class="col-lg-6" id="narrative">
			<div class="form-inline">
				<%= form_tag(comment_add_path(@narrative.id), method: "post", remote: true) do %>
				<div class="input-group">
					<%= text_field_tag(:user_submitted_comment, nil, placeholder: "Votre commentaire / Your comment", class: "form-control") %>
					<span class="input-group-btn">
						<%= button_tag(type: "submit", class: "btn btn-default") do %>
							<span class="glyphicon glyphicon-comment"></span>
						<% end %>
					</span>
					</div>
				<% end %>
			</div>
	</div>
	<div id="comments-container">
		<%= render "comments"%>
	</div>
	<div>
		<span><b>Crée/Created:</b> <%= @narrative.create_time %></span>
	</div>
	
	<!-- Popup for flag reason-->
	<%= render 'flag' %>
</div>

app/views/narratives/setting.html.erb
    <!-- <div class="navbar navbar-inverse navbar-fixed-top" role="navigation"> -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand">VousDélibérez! <span class="glyphicon glyphicon-flash"></span> YouDeliberate!</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="list-spacer">&nbsp;</li>
            <li><a class="fancybox" href="<%= admin_list_path %>">Récits <span class="glyphicon glyphicon-flash"></span> Narratives</a></li>
            <li><a class="fancybox" href="<%= admin_setting_path %>">paramètres <span class="glyphicon glyphicon-flash"></span> Settings</a></li>
            <li class="list-spacer">&nbsp;</li>
            <li class="list-spacer" align="right"><%= link_to "Déconnexion/Logout", signout_path, method: "delete" %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    

	<!-- content container -->
    <div class="container">

      <!-- page headline -->
      <div class="header-section"><br/></div>

      <!-- Upload narrative section -->
      <div class="col-lg-12">
      	<div class="panel panel-primary">
          <div class="panel-heading"><h4>Réglage&nbsp;&nbsp;<span class="glyphicon glyphicon-flash"></span>&nbsp;&nbsp;Settings</h4></div>
          <div>
            <p class="title">Change my password:</p>
			<%= form_tag(change_password_path, method: "post") do %>
				<p class="form-label"><strong>New Password: </strong><span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
			    <%= password_field_tag(:password, nil, placeholder: 'New password') %>
			    </p>
			    <p class="form-label"><strong>Confirm Password: </strong>
			    <%= password_field_tag(:password_confirmation, nil, placeholder: 'New password again') %>
			    </p>
			    <div class="with-left-margin with-bottom-margin">
			            <%= submit_tag("Change", class: "btn btn-large btn-primary") %>
			    </div>
			<% end %>
		  </div>
		  <div class="divider"></div>
		  <div>
            <p class="title">Add new administrator:</p>
			<%= form_tag(add_admin_path, method: "post") do %>
				<p class="form-label"><strong>Email adress: </strong><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
			    <%= email_field_tag(:email, nil, placeholder: 'Email') %>
			    </p>
				<p class="form-label"><strong>Password: </strong><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
			    <%= password_field_tag(:password, nil, placeholder: 'Password') %>
			    </p>
			    <p class="form-label"><strong>Confirm Password: </strong>
			    <%= password_field_tag(:password_confirmation, nil, placeholder: 'Password again') %>
			    </p>
			    <div class="with-left-margin with-bottom-margin">
			            <%= submit_tag("Add", class: "btn btn-large btn-primary") %>
			    </div>
			<% end %>
		  </div>
		  <div class="divider"></div>
		  <div>
            <p class="with-left-margin title">Google Analytics</p>
            <a class="with-left-margin with-bottom-margin btn btn-large btn-primary" href="http://www.google.ca/analytics/" target="_blank">Metrics</a>
		  </div>
      	</div>
      </div><!-- End upload narrative section -->
    </div>

app/views/narratives/show.html.erb
<p id="notice"><%= notice %></p>
<p>
<strong>Nar name:</strong>
<%= @narrative.nar_name %>
 </p>

 <p>
<strong>Nar path:</strong>
<%= @narrative.nar_path %>
 </p>

 <p>
<strong>Language:</strong>
<%= @narrative.language_id %>
 </p>

 <p>
<strong>Category:</strong>
<%= @narrative.category_id %>
 </p>

 <p>
<strong>First image:</strong>
<%= @narrative.first_image %>
 </p>

 <p>
<strong>Num of view:</strong>
<%= @narrative.num_of_view %>
 </p>

 <p>
<strong>Num of agree:</strong>
<%= @narrative.num_of_agree %>
 </p>

 <p>
<strong>Num of disagree:</strong>
<%= @narrative.num_of_disagree %>
 </p>

 <p>
<strong>Num of flagged:</strong>
<%= @narrative.num_of_flagged %>
 </p>

 <p>
<strong>Create time:</strong>
<%= @narrative.create_time %>
 </p>

 <%= link_to 'Edit', edit_narrative_path(@narrative) %> |
 <%= link_to 'Back', narratives_path %>