config/routes.rb
App60::Application.routes.draw do
  # User
  root 'user#index'
  get 'user' => redirect('/')
  get 'user/index' => redirect('/')
  get 'user/about', as: 'about'
  get 'user/contact', as: 'contact'
  get 'user/tutorial', as: 'tutorial'
  get 'share/:id', to: 'user#index', as: 'share_narrative'

  # Narratives
  get 'sunburst' => 'narratives#sunburst'
  get 'narratives/:id/play', to: 'narratives#play', as: 'play_narrative'
  post 'narratives/:id/comment/', to: 'narratives#comment', as: 'comment_add'
  delete 'narratives/:id/comment/:comment_id/remove/', to: 'narratives#remove_comment', as: 'remove_comment'
  post 'narratives/:id/flag/', to: 'narratives#flag', as: 'increment_flag'
  post 'narratives/:id/agree', to: 'narratives#agree', as: 'agree_with_narrative'
  post 'narratives/:id/undo_agree', to: 'narratives#undo_agree', as: 'undo_agree_with_narrative'
  post 'narratives/:id/disagree', to: 'narratives#disagree', as: 'disagree_with_narrative'
  post 'narratives/:id/undo_disagree', to: 'narratives#undo_disagree', as: 'undo_disagree_with_narrative'
  post 'narratives/save', as: 'save_narratives'
  resources :narratives

  # Admin
  get 'admin', to: 'narratives#index', as: 'admin_list'
  get 'admin/setting', to: 'narratives#setting', as: 'admin_setting'
  post 'admin/change', to: 'admin#change_password', as: 'change_password'
  post 'admin/add', to: 'admin#add_admin', as: 'add_admin'
  get 'admin/login',  to: 'sessions#new', as: 'signin'
  delete 'admin/logout', to: 'sessions#destroy', as: 'signout'
  post 'admin/upload', as: 'upload_narrative'
  get 'admin/forget', to: 'sessions#forget_password', as: 'forget_password'
  post 'admin/send', to: 'sessions#send_password', as: 'send_password'
  get 'admin/*any' => redirect('/admin')
  resources :sessions, only: [:new, :create, :destroy]
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  	@popover_contents = render_to_string(partial: "tutorial_popover")
    selected_narrative_id = params[:id]
    if !selected_narrative_id.nil? and !Narrative.exists?(selected_narrative_id)
      flash[:error] = "Shared narrative doesn't exist anymore"
      redirect_to root_path
    end
  end
end

app/views/user/_tutorial_popover.html.erb
<h1><small>Bienvenue au portail <%= t :portal_topic, locale: :fr %></small></h1>
<div class="panel panel-default">
  <div class="panel-body">
    Nous vous suggerons fortement de regarder notre tutoriel expliquant comment utiliser le portail. S'il-vous plaît selectionner l'icône <span class="glyphicon glyphicon-info-sign"></span> ci-dessus pour regarder le tutoriel.
  </div>
</div>
<h1><small>&nbsp;Welcome to <%= t :portal_topic, locale: :en %> portal</small></h1>
<div class="panel panel-default">
  <div class="panel-body"> 
    We strongly suggest that you watch our tutorial video to learn how to use this web portal. Please click on the <span class="glyphicon glyphicon-info-sign"></span> icon above to watch the video!
  </div>        
</div>
<div>
  <button type="button" class="btn">Close</button>
</div>

app/views/user/about.html.erb
<div class="container">
    <h2>À Propos<span class="glyphicon glyphicon-flash"></span>About us</h2>
  <ul class="nav nav-tabs">
    <li class="active"><a href="#french-video" data-toggle="tab"><%= image_tag("FR-24.png", id:"gb-flag") %></a></li>
    <li><a href="#english-video" data-toggle="tab"><%= image_tag("EN-24.png", id:"gb-flag") %></a></li>
  </ul>
  <div class="tab-content">   
    <%= t :about_html, locale: :fr %>
    <%= t :about_html, locale: :en %>
  </div>
</div><!-- /.container -->

app/views/user/contact.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-5">
			<h3>Nous Rejoindre <span class="glyphicon glyphicon-flash"></span> Contact us</h3>
			<hr>
			<address>
			<span class="glyphicon glyphicon-envelope"></span><a href="mailto:#"> teamB@youdeliberate.com</a><br><br>
			<span class="glyphicon glyphicon-earphone"></span> (555)123-4567
			</address>
		</div>		
	</div>
</div>

app/views/user/index.html.erb
<!-- nav bar -->
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">VousDélibérez! <span class="glyphicon glyphicon-flash"></span> YouDeliberate!</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="list-spacer">&nbsp;</li>

        <li>
          <%= link_to about_path, :class => 'fancybox', :'data-fancybox-type' => 'iframe' do %>
            À Propos <span class="glyphicon glyphicon-flash"></span> About
          <% end %>
        </li>

        <li>
          <%= link_to contact_path, :class => 'fancybox', :'data-fancybox-type' => 'iframe' do %>
            Nous Rejoindre <span class="glyphicon glyphicon-flash"></span> Contact Us
          <% end %>
        </li>

        <li>
          <%= link_to tutorial_path, :class => 'fancybox',:id=>'tutorial', :'data-fancybox-type' => 'iframe' do %>
            Regarder Tutoriel <span class="glyphicon glyphicon-info-sign"></span> Watch Tutorial 
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- end nav bar -->

<!-- content container -->
<div class="container" id="content-container">

  <!-- page headline -->
  <div class="header-section"></div>

  <!-- Left Column: Sunburst, Sort and Legend -->
  <div class="col-lg-4">
    <!-- Legend Panel -->
    <div class="panel panel-primary">
      <div class="panel-heading"><span><h4>Légende&nbsp;<span class="glyphicon glyphicon-flash"></span>&nbsp;Legend<span></h4></div>  
      <div class="panel-body">
        <table>
          <tr>
            <td>
              <span class="label label-against">&nbsp;&nbsp;</span>
            </td>
            <td>&nbsp;Contre&nbsp;<span class="glyphicon glyphicon-flash"></span>&nbsp;Against </td>
          </tr>
          <tr>
            <td>
              <span class="label label-for">&nbsp;&nbsp;</span>
            </td>
            <td>&nbsp;Pour&nbsp;<span class="glyphicon glyphicon-flash"></span>&nbsp;For</td>
          </tr>
          <tr>
            <td>
              <span class="label label-ambivalent">&nbsp;&nbsp;</span>
            </td>
            <td>&nbsp;Ambivalent(e)&nbsp;<span class="glyphicon glyphicon-flash"></span>&nbsp;Ambivalent</td>
          </tr>
        </table>
      </div>            
    </div>
    <!-- End Legend Panel -->

    <!-- Sunburst & Sort Panel -->
    <div class="panel panel-primary">
      <div class="panel-heading"><h4>Filtrer les récits!&nbsp;&nbsp;<span class="glyphicon glyphicon-filter"></span>&nbsp;&nbsp;Filter narratives!</h4></div>
        <div class="panel-body">
          <div id="sunburst"><!-- magic scripts put sunburst here --></div>
        </div>
        <div class="panel-footer">
	        <table>
          	<tr>
              <td class='label-filter'><span><font size="3.75">Trier&nbsp;</font><span class="glyphicon glyphicon-sort"></span><font size="3.75">&nbsp;Sort:</font><span></td>
        			<td class='button'>
        				<div class="btn-group btn-group-justified" id="tooltip-sort">
        				  <div class="btn-group"><button type="button" class="btn btn-primary btn-lg sort-select " onclick="sortClassToggle(this)" id="sort-by-views" data-toggle="tooltip" data-placement="top" title="plus de visites&nbsp;<span class='glyphicon glyphicon-flash'></span>&nbsp; most views"><span class="glyphicon glyphicon-eye-open"></span></button></div>
        				  <div class="btn-group"><button type="button" class="btn btn-default btn-lg sort-select" onclick="sortClassToggle(this)" id="sort-by-time"  data-toggle="tooltip" data-placement="top" title="plus recent &nbsp;<span class='glyphicon glyphicon-flash'></span>&nbsp; most recent"><span class="glyphicon glyphicon-time"></span></button></div>
        				  <div class="btn-group"><button type="button" class="btn btn-default btn-lg sort-select" onclick="sortClassToggle(this)" id="sort-by-agrees"  data-toggle="tooltip" data-placement="top" title="plus d'accord &nbsp;<span class='glyphicon glyphicon-flash'></span> &nbsp;most agrees"><span class="glyphicon glyphicon-thumbs-up"></span></button></div>
                  <div class="btn-group"><button type="button" class="btn btn-default btn-lg sort-select" onclick="sortClassToggle(this)" id="sort-by-disagrees"  data-toggle="tooltip" data-placement="top" title="plus desaccord &nbsp;<span class='glyphicon glyphicon-flash'></span> &nbsp;most disagrees"><span class="glyphicon glyphicon-thumbs-down"></span></button></div>
        				  <div class="btn-group"><button type="button" class="btn btn-default btn-lg sort-select" onclick="sortClassToggle(this)" id="sort-by-comments"  data-toggle="tooltip" data-placement="top" title="Plus de commentaire&nbsp; <span class='glyphicon glyphicon-flash'></span>&nbsp; most comments"><span class="glyphicon glyphicon-comment"></span></button></div>
        				</div>
        			</td>
            </tr>
            <tr>
              <td class='label-filter'><span id="label-filter"><font size="3.75">Langue <span class="glyphicon glyphicon-headphones"></span> Language:</font><span></td>
              <td class='button'>
        				<div class="btn-group btn-group-justified" id="tooltip-filter">
        				  <div class="btn-group"><button type="button" class="btn btn-default btn-lg lang-select" onclick="filterLanguageToggle(this)" id="filter-french"  data-toggle="tooltip" data-placement="top" title="Francais &nbsp;<span class='glyphicon glyphicon-flash'></span>&nbsp; French"><%= image_tag("FR-24.png", id:"gb-flag") %></button></div>
        				  <div class="btn-group"><button type="button" class="btn btn-default btn-lg lang-select" onclick="filterLanguageToggle(this)" id="filter-english"  data-toggle="tooltip" data-placement="top" title="Anglais &nbsp;<span class='glyphicon glyphicon-flash'></span>&nbsp; English"><%= image_tag("EN-24.png", id:"gb-flag") %></button></div>
        				  <div class="btn-group"><button type="button" class="btn btn-primary btn-lg lang-select" onclick="filterLanguageToggle(this)" id="filter-bilingual"  data-toggle="tooltip" data-placement="top" title="Francais & Anglais &nbsp;<span class='glyphicon glyphicon-flash'></span>&nbsp; French & English"><%= image_tag("FR-EN-24.png", id:"frgb-flag") %></button></div>
        				</div>	
              </td>
            </tr>
          </table>
        </div>
      </div>
      <!-- End of Sunburst & Sort Panel -->
  </div> 
  <!-- End Left Column -->

  <!-- Right Column: Bubbles and Language Selection -->
  <div class="col-lg-8">
    <div class="panel panel-primary">
      <div class="panel-heading" id="narratives-panel"><h4>Cliquez sur une bulle pour entendre un récit!&nbsp;&nbsp;<span class="glyphicon glyphicon-headphones"></span>&nbsp;&nbsp;Click on a bubble to hear a narrative!</h4></div>
      <div class="panel-body" id="bubble-inner-panel">
        <div id="bubbles"></div>
      </div>
    </div>
  </div> 
  <!-- End Right Column -->

</div>
<!-- End content container -->
<% content_for(:head) do %>
<!--[if lte IE 8]><%= javascript_include_tag "r2d3" %><![endif]-->
<!--[if gte IE 9]><!-->
<!--Put javascript load at end doc to let browser render dom first-->

<%= javascript_include_tag "d3.v3.min" %>
<!--<![endif]-->
<%= javascript_include_tag "functions" %>
<%= javascript_include_tag "bubbles" %>
<%= javascript_include_tag "sunburst" %>
<% end %>

<script type="text/javascript">
	jQuery(document).ready(function() {
	   jQuery('#tooltip-sort .btn').tooltip({html :true,container:'body'});
	   jQuery('#tooltip-filter .btn').tooltip({html:true,container:'body'});
<% if params[:id] %>
		window.playNarrative(<%= params[:id] %>);
<% end %>
	});
</script>

app/views/user/tutorial.html.erb
<div class="container">
	  <h2>Video tutoriel<span class="glyphicon glyphicon-flash"></span>Tutorial Video</h2>
	<ul class="nav nav-tabs">
	  <li class="active"><a href="#french-video" data-toggle="tab"><%= image_tag("FR-24.png", id:"gb-flag") %></a></li>
	  <li><a href="#english-video" data-toggle="tab"><%= image_tag("EN-24.png", id:"gb-flag") %></a></li>
	</ul>
	<div class="tab-content">		
		<div class="tab-pane active" id="french-video">
		</br>
			<iframe width="747" height="420" src="//www.youtube.com/embed/VGYPQEekAro" frameborder="0" allowfullscreen></iframe>
		</div>	
		<div class="tab-pane" id="english-video">
		</br>
			<iframe width="747" height="420" src="//www.youtube.com/embed/K92cJXd-hU4" frameborder="0" allowfullscreen></iframe>
		</div>
	</div>
	
</div>